--- #YAML:1.0
name:               Google-Charts
version:            0.01
abstract:           Perl extension for Google Charts web service
author:
    - NRG <nrg@cpan.org>
license:            unknown
distribution_type:  module
configure_requires:
    ExtUtils::MakeMaker:  0
requires:
    Encode:          0
    Exporter::Lite:  0
no_index:
    directory:
        - t
        - inc
generated_by:       ExtUtils::MakeMaker version 6.48
meta-spec:
    url:      http://module-build.sourceforge.net/META-spec-v1.4.html
    version:  1.4
